### ISSUE TITLE
Risk Analysis

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#171]

**Comment by JDixmier** [comment]
https://www.monservicesecurise.ssi.gouv.fr/service/0012ffa1-678f-4939-9ea3-bb21afc58779/descriptionService

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/171?planning-poker) with Zenhub @ad2ien @JDixmier
