### ISSUE TITLE
Ask more info to CHRU and ICL about the beta-testers and frame of the experimentation

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#173]

**Comment by JDixmier** [comment]
- [ ] Who will be the beta-testers ? List of users
Display name / mail / job title / matrix id
- [ ] Will it be a mobile use ? Laptop ? Web ? 
- [ ] Will it be with actual data or fake data ? 
- [ ] Do they have firewall that may block the access to Element ? network security policies ? 
- [ ] What is the frame of the experimentation ? 
Should we setup some by default rooms ? 
How do users interact ? 
- [ ] Documentation to produce ?

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/173?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by heroinedor** [comment]
This ticket is only about gathering information.
The consequencies of the information will be treated in other tickets
