### ISSUE TITLE
Metrics for experimentation

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#174]
- [x] Define the metrics needed to analyse the experimentation:

- [x] For the metrics available on grafana : make the graphs

- [ ] For the other metrics make a form

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/174?planning-poker) with Zenhub @JDixmier @ad2ien

**Comment by ad2ien** [comment]
Trying things out on [develop env](https://monitoring.develop.eimis.incubateur.net/d/000000012/synapse?orgId=1&from=now-3h&to=now&var-datasource=default&var-bucket_size=1h&var-instance=10.2.1.19:9090&var-job=All&var-index=All)

**Comment by ad2ien** [comment]
Here's a first version of a dashboard that could help us follow the progress of the experiment [grafana-eimis-experimentation.json](https://github.com/eimis-ans/eimis-synapse/files/12914187/grafana-eimis-experimentation.json)
