### ISSUE TITLE
Plan our action at semaine de la e-santé 

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#175]

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/175?planning-poker) with Zenhub @ad2ien @AudeNLowpital @JDixmier

**Comment by ad2ien** [comment]
About the projectathon https://industriels.esante.gouv.fr/produits-et-services/ci-sis-cadre-d-interoperabilite-des-systemes-d-information-de-sante/projectathon-interoperabilite make sense to be there, we could:
- find new partners by showing how easy it is to add a IM functionality based on MX
- good opportunity to talk about architecture hypothesis with IM providor
- same with ANS and GRADS tech people

And it would be interesting for us (dev) to know more about the CI-SIS...

**Comment by JDixmier** [comment]
Communication about the workshop : 

- [ ] Social networks
- [ ] Mail to partners 
- [ ] ANS official communication
