### ISSUE TITLE
Fix docker image versions

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#185]
This ticket to make sure synapse and element image versions are settle at least for prod and preprod.

Which is not the case currently as we are suspiciously up to date using [ananace's charts](https://gitlab.com/ananace/charts/)

We should also settle the version of the charts

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/185?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
We should also settle the version of Prometheus and Grafana
