### ISSUE TITLE
How could we set up a Mipih<> ?? experiment ?

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#189]
DoD : 2nd experiment is designed 

- [ ] Who would be the beta-testers ? 
- [ ] Which other solution would be used ? 
- [ ] Which usecase ? 
- [ ] Where ? 
- [ ] When ?

- [x] Talk with GRADeS (Bretagne, Occitanie, Grand Est)
- [x] Meeting Mipih <> PL <> EIMIS

**Comment by JDixmier** [comment]
none

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/189?planning-poker) with Zenhub @ad2ien @JDixmier
