### ISSUE TITLE
Bridge / Architecture : Questions for Yoan and Mathieu

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#201]
Get a list of questions to submit to Yoan and Mathieu about : 
- a bridge that manipulate real users
- - .....
- 

Dod : 
- question list 
- Responses form Mathieu and Yoan

**Comment by JDixmier** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/201?planning-poker) with Zenhub @JDixmier @ad2ien @heroinedor
