### ISSUE TITLE
Error when bumping terraform version to v1.6

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#202]
There's a breaking change somewhere with terraform 1.6 : investigate, fix and update if possible.

```
│ Error: Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods. See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications. Errors: 2 errors occurred:
│       * retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts.gra.amazonaws.com/": dial tcp: lookup sts.gra.amazonaws.com on 10.13.13.1:53: no such host
│       * retrieving account information via iam:ListRoles: operation error IAM: ListRoles, https response error StatusCode: 403, RequestID: a2d3bb0b-xxxxxxc2-4986-9ab6-e19be5fc82ac, api error InvalidClientTokenId: The security token included in the request is invalid.
```

**Comment by ad2ien** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/202?planning-poker) with Zenhub @heroinedor

**Comment by heroinedor** [comment]
Several modifications made on the branche : https://github.com/eimis-ans/eimis-synapse/tree/fix/202-error-when-bumping-terraform-version-matabiau-deployed
But there seems to have a bug with the OVH implementation of S3 standard :
- https://github.com/hashicorp/terraform/issues/34053
- https://github.com/hashicorp/terraform/issues/33847#issuecomment-1783896143

So an issue has been opened on the OVH support : https://help.ovhcloud.com/csm?id=csm_ticket&table=sn_customerservice_case&sys_id=1d549e41759e75902d4c32fff0ebf0f3

**Comment by ad2ien** [comment]
Maybe it's worth updating ovh provider : https://github.com/ovh/terraform-provider-ovh/releases/tag/v0.35.0

**Comment by ad2ien** [comment]
doesn't work with terraform 1.6.3 either
