### ISSUE TITLE
Make sure Mipih is technically ready to join EIMIS

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#203]
Contact MIPIH to make sure they can use EIMIS homeserver (in a centralized way)

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/203?planning-poker) with Zenhub @JDixmier @ad2ien

**Comment by ad2ien** [comment]
Meeting done:
- PSC not enough for every mipih users:
  - synapse configuration of mipih's keycloak for the experimentation
  - EIMIS keycloak and keycloak federation could be explored

tech meeting to come...
