### ISSUE TITLE
Alerting on Infrastructure components

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#212]
- Setup and refine alert levels
- Find the best way to receive this alerts : MX room, tchap, mattermost, email?

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/212?planning-poker) with Zenhub @ad2ien

**Comment by ad2ien** [comment]
Alerts are already created by default and by env. Ex: https://monitoring.preprod.eimis.incubateur.net/alerting/list

**Comment by ad2ien** [comment]
Let's start with just, setting a contact point with brevo and adjusting/analyzing the already firing alerts.

**Comment by ad2ien** [comment]
duplicated by #376 #381
