### ISSUE TITLE
Code review process improvement

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#216]
Improve Code review process so that it is mandatory and not possible to bypass

Tasklist :
- [x] protect develop the same way as preprod and main
- [x] block the possibility to bypass PR
- [x] set develop branch as default

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/216?planning-poker) with Zenhub @ad2ien

**Comment by ad2ien** [comment]
Done on eimis-synapse repo!
