### ISSUE TITLE
2FA on OVH and github  for everyone

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#217]
Does everybody have 2FA activated ?

## On github

 - [x] @heroinedor 
 - [x] @JDixmier 
 - [x] @AudeNLowpital 
 - [x] @ad2ien 

## On ovh

- [x] @heroinedor 
 - [x] @JDixmier 
 - [x] @ad2ien

**Comment by ad2ien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/217?planning-poker) with Zenhub @heroinedor @JDixmier
