### ISSUE TITLE
Document editors journey and create a template with it for next editors

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#248]
Documentation about editors journey as a user of EIMIS infrastructure : 
- [ ] how did we work together ? 
- [ ] what are the important steps ? 
- [ ] Technical characteristics to understand ?
- [ ] the mistakes to avoid ? 
- [ ] which rituals ? important meetings ? 
- [ ] how to identify beta-testers ? set up experimentation ?

Idea: Do something similar  to the Prosanté Connect onboarding process. cf. https://industriels.esante.gouv.fr/produits-et-services/pro-sante-connect "Etapes de raccordement à Pro Santé Connect"

**DoD:** Use these learnings to create a template about the steps to follow to integrate editors to EIMIS

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/248?planning-poker) with Zenhub @ad2ien @heroinedor @JDixmier

**Comment by JDixmier** [comment]
+ add our own experience

**Comment by ad2ien** [comment]
Some technical info already there : https://github.com/eimis-ans/eimis-synapse/wiki
We should add organizational topic.
A first team workshop is planned...

**Comment by JDixmier** [comment]
Work document is on Miro 

Next step : 

- [ ] Summary of an editor's journey with steps to follow and milestones (to be published on Github) 
- [ ] Deepen each step with a dedicated page with more details (good practices and misktakes to avoid)

**Comment by ad2ien** [comment]
Wiki version : https://github.com/eimis-ans/eimis-synapse/wiki/Le-parcours-%C3%A9diteur-%F0%9F%A7%B3
