### ISSUE TITLE
Preprod instance may be somewhat too open

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#271]
## State of preprod homeserver

Thanks to awesometechnologies/synapse-admin we realized that our HS is federated with a ton of other homeservers and that some non eimis related users are using it.

Not an emergency but we should somehow restrict access to staging environments. 

## Possible actions 

_order by drasticity level_

- [x] activate white list for preprod
- [x] deactivate users who registered with temporary e-mail
- [x] activate default join room

**Comment by ad2ien** [comment]
Whitelist activated for preprod, I added arch MC2 staging domain

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/271?planning-poker) with Zenhub @JDixmier @ad2ien

**Comment by ad2ien** [comment]
Here's the issue for instance reset: #286

**Comment by ad2ien** [comment]
`auto_join_rooms` config is activated only for discovery rooms.

-> Add an optional default/welcome room as parameter. @heroinedor @JDixmier is it ok with you?

If so, any ideas about aliases for this room in preprod? in prod?
