### ISSUE TITLE
Bump dependency versions

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#278]
There's some dependencies that need to be updated:

- [x] **Kubernetes : 1.26 -> 1.29**
- [x] Terraform -> 1.6.6
- [x] s3 media repo module : 1.2.1 -> 1.3.0 (maybe try the chart ? https://gitlab.com/ananace/charts/-/tree/master/charts/matrix-media-repo?ref_type=heads )
- [x] synapse chart : 3.7.7 -> 3.7.14
- [x] element chart : 1.3.2 -> 1.3.9
- [x] prometheus chart : 51.2.0 -> 55.5.0
- [x] external-dns : 0.13.6 -> 0.14.0
- [x] cert-manager chart : 1.11.0 -> 1.13.3
- [x] ingress controller chart : 4.7.1 -> 4.9.0

Synapse is now hosted by element-hq github org :

- [ ] check if there's some implications
- [ ] update links in code and docs

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/278?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
For kubernetes version bump with terraform, only next minor version bump is allowed. So we'll have to set the version to 1.28, deploy, set the version 1.29 and deploy again.

**Comment by heroinedor** [comment]
1.28 is the maximum version that we can install for now at OVH.
develop and preprod are now at this version.
