### ISSUE TITLE
Follow up on PSC prod test accounts

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#281]
Todo:
- [x] Clarify our position with ANS : are we an editor or not ?
- [x] See with Sabri what we can do ?

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/281?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by heroinedor** [comment]
Impossible to get  eCPS test card to test connexion between Prosanté Connect and EIMIS.
We will have to ask a real Healthcare Professional to get his card ....

**Comment by ad2ien** [comment]
Check with ANS to get CPA cards..

**Comment by JDixmier** [comment]
1rst intent = failure - We have to ask Anna Livia to do it herself because we cannot ask on her behalf

**Comment by heroinedor** [comment]
When Eimis will be in production, the first tests on PSC plugin will be done with Edouard and Sabri CPS card.
