### ISSUE TITLE
Find out AGPL licencing implications

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#287]
In order to assess the implications of Synapse licence change on IM editors, we'd need to get legal advise.

More precisely:

- Should Synapse modules be automatically AGPL?
- Should bridges be AGPL?
- Check licences pricing to avoid open source constraints
- ...

**Comment by ad2ien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/287?planning-poker) with Zenhub @heroinedor @JDixmier

**Comment by heroinedor** [comment]
message already posted on our mattermost : https://mattermost.incubateur.net/betagouv/pl/bo78ec6r9fre7kixqp9r1sb8ah

**Comment by heroinedor** [comment]
As the implications for EIMIS team and editors are different, we will check with DINUM/ANS legal department the implications for EIMIS.
For editors we will redirect them to their own legal department.
