### ISSUE TITLE
2FA for non Prosanté Connect user for experimentation

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#305]
Looks like the right way is do use OIDC so we should:

- deploy back keycloak
- make it use the already existing postgres DB
- configuration:
  - deactivate auto registration
  - configure 2FA, 2nd factor being the e-mail
  - fine tuning & testing

**Comment by ad2ien** [comment]
PR: #308

⚠ Don't close this before preprod merging : 

> - [x] to modify `SMTP_NOTIFY_FROM`  -> `SMTP_DISPLAY_NAME`, `SMTP_FROM` 
> - [x] add  `KEYCLOAK_CLIENT_ID` and `KEYCLOAK_CLIENT_SECRET`
> - [x] `KEYCLOAK_SUBDOMAIN_NAME`
