### ISSUE TITLE
Update keycloak version

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#319]
This PR https://github.com/eimis-ans/eimis-synapse/pull/308 introduces keycloak as ID provider with e-mail 2FA for Matrix users.

This issue is about updating keycloak version to 23. The image is ready : https://github.com/eimis-ans/eimis-keycloak but there are 2 obstacles to overcome:
- after version 22 the keycloak realm import operator adds `--optimized` arg in the import command that no longer exists in kc.sh script
- somehow if the jar spi is built in a dockerfile stage, and although it's working good with the docker compose, it gets stuck without any error message in k8s

And once it works there's some test docker images to clean up.

**Comment by ad2ien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/319?planning-poker) with Zenhub @heroinedor @ad2ien

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/319?planning-poker) with Zenhub @JDixmier
