### ISSUE TITLE
Send a Workshop + Demo proposal to ANS for Santexpo

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#321]

**Comment by JDixmier** [comment]
- [ ] Submit idea to EIMIS Team
- [ ] Brainstorm
- [ ] Submit proposal to ANS

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/321?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by heroinedor** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/321?planning-poker) with Zenhub @heroinedor
