### ISSUE TITLE
Access rights screen after delegated login

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#338]
After logging through a delegated authentication and before reaching element app a screen is displayed.
It's meant to list the access rights given to Synapse. 

Here, Synapse only gets first and last name and an id to create a matrix account. But the information displayed can be confusing for the user.

TODO : 
- [x] is it possible to suppress this screen and get to the next directly
- [x] if not, is it possible to customize this sreen and how ?

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/338?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
It possible: https://matrix-org.github.io/synapse/latest/templates.html#html-page-templates-for-single-sign-on-sso

**Comment by ad2ien** [comment]
a ticket to customize synapse docker image : #360

**Comment by ad2ien** [comment]
merged, looks good!
