### ISSUE TITLE
Apply PSC graphic design

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#340]
Match pro santé connect graphic design as closely as possible :

https://industriels.esante.gouv.fr/produits-et-services/pro-sante-connect/charte-graphique-pro-sante-connect

- [ ] "S'identifier avec PRO SANTE CONNECT" in the button text

**Comment by heroinedor** [comment]
Impossible to do in a simple way with Matrix without entering into heavy development
