### ISSUE TITLE
REC12 User whitelisting

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#343]
- After meeting with Laurent we should know:
  - The field to filter on
  - How to test

- [ ] Then write a Synapse module to do the job -> new repo!
- [ ] Include this module in our stack

This filter should be done through the user mapping provider : https://matrix-org.github.io/synapse/latest/sso_mapping_providers.html

Basic architecture : 
- user listing stored in S3, loaded at synapse start. Each update of this list will need a restart of synapse. 
- the custom user mapping provider (https://github.com/eimis-ans/eimis-prosante-connect-module) check if the incoming signed user is present in this list. The discriminant identifier should be the user's email.
- if it is => login accepted
- if not => display of an error page saying that he is not in the user list

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/343?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
Tchap did something similar somewhere there : https://github.com/tchapgouv?q=&type=all&language=python&sort=

**Comment by JDixmier** [comment]
**Goal : PSC users cannot auto register, they have to be whitelisted**

**Comment by ad2ien** [comment]
Information we need is not in the token argument. In `map_user_attributes`  we'll need to use `access_token` part to ask PSC userinfo endpoint for more info.

doc:
- https://industriels.esante.gouv.fr/produits-et-services/pro-sante-connect/documentation-technique
- https://industriels.esante.gouv.fr/produits-et-services/pro-sante-connect/userinfo
