### ISSUE TITLE
keycloak logout and login again

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#346]
Make the following work:

- login with keycloak
- logout in element
- try to login again

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/346?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
Take advantage of this to configure back channel logout and check that when logged out from keycloak the user is also logged out from synapse

**Comment by ad2ien** [comment]
Doc about keycloak logout : https://www.keycloak.org/docs/latest/upgrading/index.html#openid-connect-logout apparently it's good practice to manually logout from keycloak

**Comment by ad2ien** [comment]
PR done, tests :

- [x] login with keycloak
- [x] logout redirects to keycloak logout screen (for manual logout)
- [x] If the user doesn't log out from keycloak he/she can swiftly log in again
- [x] Ending the session in keycloak, disconnects the user in element
