### ISSUE TITLE
Get in touch with CH Dijon to know if interested to join with Beaune

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#350]

**Comment by ad2ien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/350?planning-poker) with Zenhub @ad2ien @heroinedor @JDixmier
