### ISSUE TITLE
Adaptation to Capgemini prod

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#352]
tasklist : 
- [x] 2 networks : EIMIS-Prod (10.35.64/24), ASIP-HDS-ADMIN (10.134.53.36-40)
- [x] load balancer Octavia with private IP on EIMIS-Prod LAN
- [x] all Kubernetes nodes on EIMIS-Prod LAN
- [x] What about TLS certificates ?
- [x] What about DNS ?
- [ ] (optional) fluentbit installed on EIMIS-Prod LAN
- [ ] What about egress flux (smtp, federation?)

Proposed architecture : 
<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFNQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa37ad2912196c667541b022cb03ed2893dc6f20/image.png" alt="image.png" />

**Comment by ad2ien** [comment]
Before preprod merge:
- delete external-dns namespace
- delete dns entry
- manage zone dns issue : different behavior  development env and develop / preprod env #394

**Comment by ad2ien** [comment]
Other tickets are opened to tackle the full compliance with prod infra
