### ISSUE TITLE
REC02 Bump dependencies versions

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#358]
Bump versions of following dependencies : 
- matrix-synapse chart : 3.7.14 -> 3.9.1
- [s3 synapse module](https://github.com/matrix-org/synapse-s3-storage-provider/releases/tag/v1.4.0)

**Comment by ad2ien** [comment]
Also check other dependencies : terrafrom providers, helm, images...

**Comment by ad2ien** [comment]
- OpenStack Provider 1.54.1
- Hashicorp AWS 5.42.0,
- Ingress Nginx controller 4.10.0

**Comment by ad2ien** [comment]
terraform providers:

- provider ovh 0.42.0
- provider openstack 1.54.1
- hashicorp/aws 5.45.0

**Comment by ad2ien** [comment]
to ensure Keycloak operator is properly updated, it needs to be destroyed first : `kubectl delete deploy keycloak-operator -n keycloak`

**Comment by ad2ien** [comment]
k8s version -> 1.29
No issues but lasts 10min to update

**Comment by ad2ien** [comment]
preprod deployed
