### ISSUE TITLE
REC07 Upload CGU

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#372]
Make CGU easily available to the users.

Suggestion:

- In an "information" read only room joined by default
- Somewhere in element-web if the setting is possible..

- [x] version CGU on infra repo, or wiki

**Comment by JDixmier** [comment]
DoD : CGU can be consulted from the Element application

**Comment by ad2ien** [comment]
@JDixmier, it would look like this (without the unappropriated "2")

![image](https://github.com/eimis-ans/eimis-synapse/assets/87697380/7c59c784-12ef-4338-b03f-cf8d74764be8)

CGU on the wiki : https://github.com/eimis-ans/eimis-synapse/wiki/CGU

**Comment by ad2ien** [comment]
Name of the room "Info experimentation", room description : "Ce canal sera utiliser pour informer sur les actualités des expérimentations"

**Comment by JDixmier** [comment]
Name of the room "Infos Expérimentation Messagerie", room description : "Ce salon sert à vous informer sur les actualités des expérimentations liées à votre messagerie instantanée". 

Message : 

**👋 Bienvenue dans l'expérimentation EIMIS sur les messageries instantanées !**

L'objectif de cette expérimentation est de faciliter les communications entre professionnels de santé, dans un cadre sécurisé et pratique. Merci beaucoup pour votre participation ! 

Vous pouvez vous servir de cette application pour vous coordonner avec d'autres professionnels et échanger des informations sur vos patients, à condition de respecter les règles de confidentialité mentionnées dans les [Conditions Générales d'Utilisation](https://github.com/eimis-ans/eimis-synapse/wiki/CGU). 

⚠️ _Attention à ne partager des données de santé de patients qu'avec des professionnels habilités à les recevoir._

**Comment by ad2ien** [comment]
Final version :
![image](https://github.com/eimis-ans/eimis-synapse/assets/87697380/5ada05dd-9c63-4009-a5c8-38ab8a83221d)
