### ISSUE TITLE
Setup alert manager part 2

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#376]
The goal of this ticket is to be able to forward alert to [Zabbix](https://www.zabbix.com/) instance that will be running in prod and will be reachable on a specific IP.

Preprod : We also need a way to process the alerts received, but it might be different from production.
=> we have to find this way. Ex: 
- Alert sent to a Tchap room
- alert dashboard like Alerta (https://alerta.io/)
- Grafana ...

**Comment by heroinedor** [comment]
Unkown point : 
Zabbix will be on admin network.
Alertmanager will be on eimis-prod network.
=> how the 2 networks will be able to communicate ?

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/376?planning-poker) with Zenhub @ad2ien @JDixmier
