### ISSUE TITLE
REC16 - User password complexity policy

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#378]
Configure keycloak to set a password complexity fitting for production : 
Realm, configure / authentication / Policy / Password policies

- report configuration in realm manifest
- mention it in architecture document

**REC16** in the risk analysis

**Comment by ad2ien** [comment]
Ask the MIPIH about its user password complexity policy and mention it in architecture document and experimentation criterias

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/378?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
Keycloak realm configured, DAT filled
