### ISSUE TITLE
REC23 - Service accounts password complexity policy

### ISSUE THREAD

**Issue by ad2ien** [tchapgouv/synapse-on-k8s#380]
Define a policy for services and technical accounts (along with the renew period). Mention it in architecture document.

Enforce them when possible.

**REC16 REC23**

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/380?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
Keycloak realm configured, DAT filled

**Comment by ad2ien** [comment]
Document filed, #386 created
