### ISSUE TITLE
Setup alert manager basic part

### ISSUE THREAD

**Issue by heroinedor** [tchapgouv/synapse-on-k8s#381]
We already have installed prometheus with prometheus helm chart. Add the alermanager alertmanager module to our stack

Some docs about it : https://www.digitalocean.com/community/developer-center/how-to-set-up-alerts-and-notification-using-alertmanager-in-doks-cluster

For the other tasks about this subject, see #376

**Comment by ad2ien** [comment]
make sure it's compliant with prod env
