### ISSUE TITLE
REC.BG.01 - PS and non-PS status visible in display name

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#400]
**Hypothèse retenue pour le 1er test : faire figurer la profession entre crochets dans le display name** 

**Pour les PS enrôlés via PSC :**
- utiliser le "code profession" et le traduire en profession selon la nomenclature PSC 
- Nomenclature : https://www.insee.fr/fr/information/6208292

**Pour les PS enrôlés via EIMIS Connect :**
- demander la profession selon la même nomenclature que PSC

**Pour les PS enrôlés via solution éditeur :** 
- à déterminer au cas par cas avec les éditeurs 
NB : si on ne parvient pas à obtenir l'info >>> pas d'info entre crochets

**Comment by heroinedor** [comment]
Can be avoided for the APE (cf. Laurent).

**Comment by ad2ien** [comment]
After #404, if there's a profession available in the userInfo, it is displayed in the display name. If not, this issue will add "🔴 (non habilité à la donnée de santé)" to the display name. (asked by ANS)
