### ISSUE TITLE
REC07 - Connexion screen : add a warning "i am aware of the use that must be done of health data..."

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#401]
First connection of every user (PSC / EIMIS Connect / Editor) >>> an intermediary screen between connection screen and homepage displays a message with the opportunity for the user to confirm its understanding of the conditions of exchanging health data 

- [x] Draft the message 
- [x] Implement it in a page between the connexion screen and the home page

**Comment by ad2ien** [comment]
What about displaying the message along with General Terms and Conditions link in a read only welcome room in which users are invited by default?

**Comment by heroinedor** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/401?planning-poker) with Zenhub @ad2ien @JDixmier

**Comment by ad2ien** [comment]
Done with #372
