### ISSUE TITLE
REC.BG.01 - Profession visible in display name for PSC users

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#404]
- [x] Get the reference table 
- [x] Implement in the user mapping

**Comment by ad2ien** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EIMIS-6419ddbd85693a00127de149/issues/eimis-ans/eimis-synapse/404?planning-poker) with Zenhub @heroinedor @JDixmier
