### ISSUE TITLE
As a EIMIS Connect user, I can reset my password

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#413]
![Capture d’écran 2024-04-30 à 16 44 49](https://github.com/eimis-ans/eimis-synapse/assets/45665538/8a5afcde-5b6c-4804-a69f-88656cf9ddc1)

![Capture d’écran 2024-04-30 à 16 43 07](https://github.com/eimis-ans/eimis-synapse/assets/45665538/a9192f03-1012-42df-850c-7a541aa68a03)

**Comment by ad2ien** [comment]
- [x] add text/password-reset.ftl template to keycloak image
- [x] configure keycloak realm to enable "forgot passeword" by default

**Comment by ad2ien** [comment]
https://github.com/eimis-ans/eimis-keycloak/pull/9 fixed the issue in keycloak
#438 modified the realm but after preprod merge, we'll still have to:
- [x] restart keycloak
- [x] Realm settings / login / Login screen customization / Forgot password = on
- [x] Realm settings / Themes / Email theme = `eimis-email`
