### ISSUE TITLE
REC12 - Document user's enrollment process 

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/synapse-on-k8s#424]

**Comment by JDixmier** [comment]
https://www.notion.so/Services-d-urgence-6dce28c80f474969bad4291833b5e922

**Comment by ad2ien** [comment]
included as well in the DAT : https://www.notion.so/DAT-exp-rimentation-58453563f06d45b1949f45d62d4bdbb1?pvs=4#e25402fbc4044f69b6171a533422e975
